# Generated by Django 4.1.4 on 2022-12-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('disciplina_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('turma_id', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appacademico.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appacademico.professor'),
        ),
    ]
