# Generated by Django 4.1.4 on 2022-12-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='turma_id',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma_id',
            field=models.ManyToManyField(related_name='turmas', to='appacademico.turma'),
        ),
    ]
