# Generated by Django 4.1.4 on 2022-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
