# Generated by Django 4.1.4 on 2022-12-17 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0002_alter_aluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appacademico.turma'),
        ),
    ]
