# Generated by Django 4.1.4 on 2022-12-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0002_remove_disciplina_turma_id_disciplina_turma_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='aluno',
            new_name='alunos',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='turma_id',
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplinas',
            field=models.ManyToManyField(related_name='disciplinas', to='appacademico.disciplina'),
        ),
    ]
