# Generated by Django 4.1.4 on 2022-12-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0002_alter_aluno_telefone_alter_professor_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='nome_disciplina',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='disciplina_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
