# Generated by Django 4.1.4 on 2022-12-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0003_disciplina_nome_disciplina_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='matricula',
            new_name='matricula_do_professor',
        ),
    ]
