# Generated by Django 4.1.4 on 2022-12-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0004_rename_matricula_disciplina_matricula_do_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='matricula_do_professor',
            new_name='professor',
        ),
    ]
