# Generated by Django 4.1.4 on 2022-12-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0006_alter_turma_turma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='disciplina_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
