# Generated by Django 4.1.4 on 2022-12-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0007_alter_disciplina_disciplina_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='matricula',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
