# Generated by Django 4.1.4 on 2022-12-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appacademico', '0008_alter_aluno_matricula_alter_professor_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
